{
	"id": "CVE-2019-9948",
	"vulnerabilities": [
		{
			"id": "CVE-2019-9948",
			"description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
						"base_score": 9.1,
						"base_severity": "CRITICAL",
						"temporal_score": 9.1,
						"temporal_severity": "CRITICAL",
						"environmental_score": 9.1,
						"environmental_severity": "CRITICAL"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2019-9948"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.securityfocus.com/bid/107549"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2019:1700"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2019:2030"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2019:3335"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2019:3520"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://bugs.python.org/issue35907"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202003-26"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.netapp.com/advisory/ntap-20190404-0004/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2019/07/msg00011.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://seclists.org/bugtraq/2019/Oct/29"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/python/cpython/pull/11842"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://usn.ubuntu.com/4127-1/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://usn.ubuntu.com/4127-2/"
				}
			],
			"published": "2019-03-23T18:29:02Z",
			"modified": "2024-05-14T06:49:46.204966Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.10",
			"vulnerable": true,
			"package": {
				"name": "python2"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.7.16-r1"
					}
				],
				"fixed": [
					"2.7.16-r1"
				]
			}
		},
		{
			"ecosystem": "alpine:3.11",
			"vulnerable": true,
			"package": {
				"name": "python2"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.7.16-r1"
					}
				],
				"fixed": [
					"2.7.16-r1"
				]
			}
		},
		{
			"ecosystem": "alpine:3.12",
			"vulnerable": true,
			"package": {
				"name": "python2"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.7.16-r1"
					}
				],
				"fixed": [
					"2.7.16-r1"
				]
			}
		},
		{
			"ecosystem": "alpine:3.7",
			"vulnerable": true,
			"package": {
				"name": "python2"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.7.15-r2"
					}
				],
				"fixed": [
					"2.7.15-r2"
				]
			}
		},
		{
			"ecosystem": "alpine:3.8",
			"vulnerable": true,
			"package": {
				"name": "python2"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.7.15-r2"
					}
				],
				"fixed": [
					"2.7.15-r2"
				]
			}
		},
		{
			"ecosystem": "alpine:3.9",
			"vulnerable": true,
			"package": {
				"name": "python2"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.7.16-r1"
					}
				],
				"fixed": [
					"2.7.16-r1"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
