{
	"id": "CVE-2019-17345",
	"vulnerabilities": [
		{
			"id": "CVE-2019-17345",
			"description": "An issue was discovered in Xen 4.8.x through 4.11.x allowing x86 PV guest OS users to cause a denial of service because mishandling of failed IOMMU operations causes a bug check during the cleanup of a crashed guest.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:H",
						"base_score": 6.5,
						"base_severity": "MEDIUM",
						"temporal_score": 6.5,
						"temporal_severity": "MEDIUM",
						"environmental_score": 6.5,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2019-17345"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://xenbits.xen.org/xsa/advisory-291.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.debian.org/security/2020/dsa-4602"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://xenbits.xen.org/xsa/advisory-291.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.openwall.com/lists/oss-security/2019/10/25/4"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://seclists.org/bugtraq/2020/Jan/21"
				}
			],
			"published": "2019-10-08T01:15:10Z",
			"modified": "2024-05-14T06:58:03.80209Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.9",
			"vulnerable": true,
			"package": {
				"name": "xen"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "4.11.2-r0"
					}
				],
				"fixed": [
					"4.11.2-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
