{
	"id": "CVE-2019-3498",
	"vulnerabilities": [
		{
			"id": "CVE-2019-3498",
			"description": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.",
			"severity": [
				{
					"type": "cvss_v30",
					"source": "security.alpinelinux.org",
					"cvss_v30": {
						"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
						"base_score": 6.5,
						"base_severity": "MEDIUM",
						"temporal_score": 6.5,
						"temporal_severity": "MEDIUM",
						"environmental_score": 6.5,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2019-3498"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.securityfocus.com/bid/106453"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://docs.djangoproject.com/en/dev/releases/security/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.debian.org/security/2019/dsa-4363"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://groups.google.com/forum/#%21topic/django-announce/VYU7xQQTEPQ"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://usn.ubuntu.com/3851-1/"
				}
			],
			"published": "2019-01-09T23:29:05Z",
			"modified": "2023-11-29T07:28:46.629223Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.10",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.18-r0"
					}
				],
				"fixed": [
					"1.11.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.11",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.18-r0"
					}
				],
				"fixed": [
					"1.11.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.12",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.18-r0"
					}
				],
				"fixed": [
					"1.11.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.6",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.18-r0"
					}
				],
				"fixed": [
					"1.11.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.7",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.18-r0"
					}
				],
				"fixed": [
					"1.11.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.8",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.18-r0"
					}
				],
				"fixed": [
					"1.11.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.9",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.18-r0"
					}
				],
				"fixed": [
					"1.11.18-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
