{
	"id": "CVE-2022-22815",
	"vulnerabilities": [
		{
			"id": "CVE-2022-22815",
			"description": "path_getbbox in path.c in Pillow before 9.0.0 improperly initializes ImagePath.Path.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
						"base_score": 6.5,
						"base_severity": "MEDIUM",
						"temporal_score": 6.5,
						"temporal_severity": "MEDIUM",
						"environmental_score": 6.5,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2022-22815"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#fixed-imagepath-path-array-handling"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202211-10"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.debian.org/security/2022/dsa-5053"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/python-pillow/Pillow/blob/c5d9223a8b5e9295d15b5a9b1ef1dae44c8499f3/src/path.c#L331"
				}
			],
			"published": "2022-01-10T14:12:54Z",
			"modified": "2024-05-14T09:52:06.646147Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.15",
			"vulnerable": true,
			"package": {
				"name": "py3-pillow"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "8.4.0-r2"
					}
				],
				"fixed": [
					"8.4.0-r2"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
