{
	"id": "CVE-2021-28675",
	"vulnerabilities": [
		{
			"id": "CVE-2021-28675",
			"description": "An issue was discovered in Pillow before 8.2.0. PSDImagePlugin.PsdImageFile lacked a sanity check on the number of input layers relative to the size of the data block. This could lead to a DoS on Image.open prior to Image.load.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
						"base_score": 5.5,
						"base_severity": "MEDIUM",
						"temporal_score": 5.5,
						"temporal_severity": "MEDIUM",
						"environmental_score": 5.5,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2021-28675"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28675-fix-dos-in-psdimageplugin"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202107-33"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
				}
			],
			"published": "2021-06-02T15:15:07Z",
			"modified": "2024-05-14T08:32:49.978346Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.14",
			"vulnerable": true,
			"package": {
				"name": "py3-pillow"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "8.2.0-r0"
					}
				],
				"fixed": [
					"8.2.0-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.15",
			"vulnerable": true,
			"package": {
				"name": "py3-pillow"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "8.2.0-r0"
					}
				],
				"fixed": [
					"8.2.0-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
